module.exports.topRated = [
  {
    Title: "The Shawshank Redemption",
    Year: "1994",
    Rated: "R",
    Released: "14 Oct 1994",
    Runtime: "142 min",
    Genre: "Drama",
    Director: "Frank Darabont",
    Writer: "Stephen King, Frank Darabont",
    Actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
    Plot: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 7 Oscars. 21 wins & 42 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "91%",
      },
      {
        Source: "Metacritic",
        Value: "82/100",
      },
    ],
    Metascore: "82",
    imdbRating: "9.3",
    imdbVotes: "2,851,631",
    imdbID: "tt0111161",
    Type: "movie",
    DVD: "15 Aug 2008",
    BoxOffice: "$28,767,189",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Godfather",
    Year: "1972",
    Rated: "R",
    Released: "24 Mar 1972",
    Runtime: "175 min",
    Genre: "Crime, Drama",
    Director: "Francis Ford Coppola",
    Writer: "Mario Puzo, Francis Ford Coppola",
    Actors: "Marlon Brando, Al Pacino, James Caan",
    Plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    Language: "English, Italian, Latin",
    Country: "United States",
    Awards: "Won 3 Oscars. 31 wins & 31 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.2/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "97%",
      },
      {
        Source: "Metacritic",
        Value: "100/100",
      },
    ],
    Metascore: "100",
    imdbRating: "9.2",
    imdbVotes: "1,988,710",
    imdbID: "tt0068646",
    Type: "movie",
    DVD: "01 Aug 2013",
    BoxOffice: "$136,381,073",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Dark Knight",
    Year: "2008",
    Rated: "PG-13",
    Released: "18 Jul 2008",
    Runtime: "152 min",
    Genre: "Action, Crime, Drama",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    Actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
    Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Language: "English, Mandarin",
    Country: "United States, United Kingdom",
    Awards: "Won 2 Oscars. 162 wins & 164 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "84/100",
      },
    ],
    Metascore: "84",
    imdbRating: "9.0",
    imdbVotes: "2,835,809",
    imdbID: "tt0468569",
    Type: "movie",
    DVD: "14 Jun 2010",
    BoxOffice: "$534,987,076",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Godfather Part II",
    Year: "1974",
    Rated: "R",
    Released: "18 Dec 1974",
    Runtime: "202 min",
    Genre: "Crime, Drama",
    Director: "Francis Ford Coppola",
    Writer: "Francis Ford Coppola, Mario Puzo",
    Actors: "Al Pacino, Robert De Niro, Robert Duvall",
    Plot: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
    Language: "English, Italian, Spanish, Latin, Sicilian",
    Country: "United States",
    Awards: "Won 6 Oscars. 17 wins & 21 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "96%",
      },
      {
        Source: "Metacritic",
        Value: "90/100",
      },
    ],
    Metascore: "90",
    imdbRating: "9.0",
    imdbVotes: "1,349,735",
    imdbID: "tt0071562",
    Type: "movie",
    DVD: "15 Sep 2012",
    BoxOffice: "$47,834,595",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "12 Angry Men",
    Year: "1957",
    Rated: "Approved",
    Released: "10 Apr 1957",
    Runtime: "96 min",
    Genre: "Crime, Drama",
    Director: "Sidney Lumet",
    Writer: "Reginald Rose",
    Actors: "Henry Fonda, Lee J. Cobb, Martin Balsam",
    Plot: "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 3 Oscars. 16 wins & 12 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "100%",
      },
      {
        Source: "Metacritic",
        Value: "97/100",
      },
    ],
    Metascore: "97",
    imdbRating: "9.0",
    imdbVotes: "851,716",
    imdbID: "tt0050083",
    Type: "movie",
    DVD: "04 Apr 2012",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Schindler's List",
    Year: "1993",
    Rated: "R",
    Released: "04 Feb 1994",
    Runtime: "195 min",
    Genre: "Biography, Drama, History",
    Director: "Steven Spielberg",
    Writer: "Thomas Keneally, Steven Zaillian",
    Actors: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
    Plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    Language: "English, Hebrew, German, Polish, Latin",
    Country: "United States",
    Awards: "Won 7 Oscars. 91 wins & 49 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "98%",
      },
      {
        Source: "Metacritic",
        Value: "95/100",
      },
    ],
    Metascore: "95",
    imdbRating: "9.0",
    imdbVotes: "1,427,588",
    imdbID: "tt0108052",
    Type: "movie",
    DVD: "05 Mar 2013",
    BoxOffice: "$96,898,818",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Lord of the Rings: The Return of the King",
    Year: "2003",
    Rated: "PG-13",
    Released: "17 Dec 2003",
    Runtime: "201 min",
    Genre: "Action, Adventure, Drama",
    Director: "Peter Jackson",
    Writer: "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
    Actors: "Elijah Wood, Viggo Mortensen, Ian McKellen",
    Plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    Language: "English, Quenya, Old English, Sindarin",
    Country: "New Zealand, United States",
    Awards: "Won 11 Oscars. 215 wins & 124 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "94/100",
      },
    ],
    Metascore: "94",
    imdbRating: "9.0",
    imdbVotes: "1,955,374",
    imdbID: "tt0167260",
    Type: "movie",
    DVD: "06 Apr 2010",
    BoxOffice: "$379,427,292",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Pulp Fiction",
    Year: "1994",
    Rated: "R",
    Released: "14 Oct 1994",
    Runtime: "154 min",
    Genre: "Crime, Drama",
    Director: "Quentin Tarantino",
    Writer: "Quentin Tarantino, Roger Avary",
    Actors: "John Travolta, Uma Thurman, Samuel L. Jackson",
    Plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    Language: "English, Spanish, French",
    Country: "United States",
    Awards: "Won 1 Oscar. 69 wins & 72 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "92%",
      },
      {
        Source: "Metacritic",
        Value: "95/100",
      },
    ],
    Metascore: "95",
    imdbRating: "8.9",
    imdbVotes: "2,191,582",
    imdbID: "tt0110912",
    Type: "movie",
    DVD: "21 Apr 2016",
    BoxOffice: "$107,928,762",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Lord of the Rings: The Fellowship of the Ring",
    Year: "2001",
    Rated: "PG-13",
    Released: "19 Dec 2001",
    Runtime: "178 min",
    Genre: "Action, Adventure, Drama",
    Director: "Peter Jackson",
    Writer: "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
    Actors: "Elijah Wood, Ian McKellen, Orlando Bloom",
    Plot: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    Language: "English, Sindarin",
    Country: "New Zealand, United States",
    Awards: "Won 4 Oscars. 125 wins & 127 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "91%",
      },
      {
        Source: "Metacritic",
        Value: "92/100",
      },
    ],
    Metascore: "92",
    imdbRating: "8.9",
    imdbVotes: "1,983,238",
    imdbID: "tt0120737",
    Type: "movie",
    DVD: "28 Jun 2011",
    BoxOffice: "$316,115,420",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Good, the Bad and the Ugly",
    Year: "1966",
    Rated: "Approved",
    Released: "29 Dec 1967",
    Runtime: "178 min",
    Genre: "Adventure, Western",
    Director: "Sergio Leone",
    Writer: "Luciano Vincenzoni, Sergio Leone, Agenore Incrocci",
    Actors: "Clint Eastwood, Eli Wallach, Lee Van Cleef",
    Plot: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
    Language: "Italian",
    Country: "Italy, Spain, West Germany",
    Awards: "2 wins & 5 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "97%",
      },
      {
        Source: "Metacritic",
        Value: "90/100",
      },
    ],
    Metascore: "90",
    imdbRating: "8.8",
    imdbVotes: "802,961",
    imdbID: "tt0060196",
    Type: "movie",
    DVD: "27 Aug 2015",
    BoxOffice: "$25,100,000",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Forrest Gump",
    Year: "1994",
    Rated: "PG-13",
    Released: "06 Jul 1994",
    Runtime: "142 min",
    Genre: "Drama, Romance",
    Director: "Robert Zemeckis",
    Writer: "Winston Groom, Eric Roth",
    Actors: "Tom Hanks, Robin Wright, Gary Sinise",
    Plot: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
    Language: "English",
    Country: "United States",
    Awards: "Won 6 Oscars. 50 wins & 74 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "71%",
      },
      {
        Source: "Metacritic",
        Value: "82/100",
      },
    ],
    Metascore: "82",
    imdbRating: "8.8",
    imdbVotes: "2,228,850",
    imdbID: "tt0109830",
    Type: "movie",
    DVD: "01 Aug 2013",
    BoxOffice: "$330,455,270",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Lord of the Rings: The Two Towers",
    Year: "2002",
    Rated: "PG-13",
    Released: "18 Dec 2002",
    Runtime: "179 min",
    Genre: "Action, Adventure, Drama",
    Director: "Peter Jackson",
    Writer: "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
    Actors: "Elijah Wood, Ian McKellen, Viggo Mortensen",
    Plot: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
    Language: "English, Sindarin, Old English",
    Country: "New Zealand, United States",
    Awards: "Won 2 Oscars. 132 wins & 138 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "95%",
      },
      {
        Source: "Metacritic",
        Value: "87/100",
      },
    ],
    Metascore: "87",
    imdbRating: "8.8",
    imdbVotes: "1,763,973",
    imdbID: "tt0167261",
    Type: "movie",
    DVD: "28 Jun 2011",
    BoxOffice: "$342,952,511",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Fight Club",
    Year: "1999",
    Rated: "R",
    Released: "15 Oct 1999",
    Runtime: "139 min",
    Genre: "Drama",
    Director: "David Fincher",
    Writer: "Chuck Palahniuk, Jim Uhls",
    Actors: "Brad Pitt, Edward Norton, Meat Loaf",
    Plot: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    Language: "English",
    Country: "Germany, United States",
    Awards: "Nominated for 1 Oscar. 12 wins & 38 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "79%",
      },
      {
        Source: "Metacritic",
        Value: "67/100",
      },
    ],
    Metascore: "67",
    imdbRating: "8.8",
    imdbVotes: "2,287,043",
    imdbID: "tt0137523",
    Type: "movie",
    DVD: "19 Nov 2014",
    BoxOffice: "$37,030,102",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Inception",
    Year: "2010",
    Rated: "PG-13",
    Released: "16 Jul 2010",
    Runtime: "148 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
    Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
    Language: "English, Japanese, French",
    Country: "United States, United Kingdom",
    Awards: "Won 4 Oscars. 159 wins & 220 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "87%",
      },
      {
        Source: "Metacritic",
        Value: "74/100",
      },
    ],
    Metascore: "74",
    imdbRating: "8.8",
    imdbVotes: "2,517,914",
    imdbID: "tt1375666",
    Type: "movie",
    DVD: "20 Jun 2013",
    BoxOffice: "$292,587,330",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Star Wars: Episode V - The Empire Strikes Back",
    Year: "1980",
    Rated: "PG",
    Released: "18 Jun 1980",
    Runtime: "124 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "Irvin Kershner",
    Writer: "Leigh Brackett, Lawrence Kasdan, George Lucas",
    Actors: "Mark Hamill, Harrison Ford, Carrie Fisher",
    Plot: "After the Rebels are overpowered by the Empire, Luke Skywalker begins his Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.",
    Language: "English",
    Country: "United States",
    Awards: "Won 1 Oscar. 26 wins & 20 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "95%",
      },
      {
        Source: "Metacritic",
        Value: "82/100",
      },
    ],
    Metascore: "82",
    imdbRating: "8.7",
    imdbVotes: "1,365,441",
    imdbID: "tt0080684",
    Type: "movie",
    DVD: "10 Apr 2015",
    BoxOffice: "$292,753,960",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Matrix",
    Year: "1999",
    Rated: "R",
    Released: "31 Mar 1999",
    Runtime: "136 min",
    Genre: "Action, Sci-Fi",
    Director: "Lana Wachowski, Lilly Wachowski",
    Writer: "Lilly Wachowski, Lana Wachowski",
    Actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    Plot: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    Language: "English",
    Country: "United States, Australia",
    Awards: "Won 4 Oscars. 42 wins & 52 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "83%",
      },
      {
        Source: "Metacritic",
        Value: "73/100",
      },
    ],
    Metascore: "73",
    imdbRating: "8.7",
    imdbVotes: "2,026,128",
    imdbID: "tt0133093",
    Type: "movie",
    DVD: "01 Jan 2009",
    BoxOffice: "$172,076,928",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Goodfellas",
    Year: "1990",
    Rated: "R",
    Released: "21 Sep 1990",
    Runtime: "145 min",
    Genre: "Biography, Crime, Drama",
    Director: "Martin Scorsese",
    Writer: "Nicholas Pileggi, Martin Scorsese",
    Actors: "Robert De Niro, Ray Liotta, Joe Pesci",
    Plot: "The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.",
    Language: "English, Italian",
    Country: "United States",
    Awards: "Won 1 Oscar. 44 wins & 38 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "92/100",
      },
    ],
    Metascore: "92",
    imdbRating: "8.7",
    imdbVotes: "1,242,337",
    imdbID: "tt0099685",
    Type: "movie",
    DVD: "15 Aug 2008",
    BoxOffice: "$46,909,721",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "One Flew Over the Cuckoo's Nest",
    Year: "1975",
    Rated: "R",
    Released: "19 Nov 1975",
    Runtime: "133 min",
    Genre: "Drama",
    Director: "Milos Forman",
    Writer: "Lawrence Hauben, Bo Goldman, Ken Kesey",
    Actors: "Jack Nicholson, Louise Fletcher, Michael Berryman",
    Plot: "In the Fall of 1963, a Korean War veteran and criminal pleads insanity and is admitted to a mental institution, where he rallies up the scared patients against the tyrannical nurse.",
    Language: "English",
    Country: "United States",
    Awards: "Won 5 Oscars. 38 wins & 15 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "93%",
      },
      {
        Source: "Metacritic",
        Value: "84/100",
      },
    ],
    Metascore: "84",
    imdbRating: "8.7",
    imdbVotes: "1,060,833",
    imdbID: "tt0073486",
    Type: "movie",
    DVD: "30 Nov 2016",
    BoxOffice: "$108,981,275",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Se7en",
    Year: "1995",
    Rated: "R",
    Released: "22 Sep 1995",
    Runtime: "127 min",
    Genre: "Crime, Drama, Mystery",
    Director: "David Fincher",
    Writer: "Andrew Kevin Walker",
    Actors: "Morgan Freeman, Brad Pitt, Kevin Spacey",
    Plot: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 29 wins & 43 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.6/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "83%",
      },
      {
        Source: "Metacritic",
        Value: "65/100",
      },
    ],
    Metascore: "65",
    imdbRating: "8.6",
    imdbVotes: "1,774,300",
    imdbID: "tt0114369",
    Type: "movie",
    DVD: "06 Jul 2010",
    BoxOffice: "$100,125,643",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "It's a Wonderful Life",
    Year: "1946",
    Rated: "PG",
    Released: "07 Jan 1947",
    Runtime: "130 min",
    Genre: "Drama, Family, Fantasy",
    Director: "Frank Capra",
    Writer: "Frances Goodrich, Albert Hackett, Frank Capra",
    Actors: "James Stewart, Donna Reed, Lionel Barrymore",
    Plot: "An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.",
    Language: "English, French",
    Country: "United States",
    Awards: "Nominated for 5 Oscars. 7 wins & 6 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.6/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "89/100",
      },
    ],
    Metascore: "89",
    imdbRating: "8.6",
    imdbVotes: "495,169",
    imdbID: "tt0038650",
    Type: "movie",
    DVD: "30 Nov 2016",
    BoxOffice: "$1,483,643",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];

module.exports.popular = [
  {
    Title: "Oppenheimer",
    Year: "2023",
    Rated: "R",
    Released: "21 Jul 2023",
    Runtime: "180 min",
    Genre: "Biography, Drama, History",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan, Kai Bird, Martin Sherwin",
    Actors: "Cillian Murphy, Emily Blunt, Matt Damon",
    Plot: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    Language: "English, German, Italian",
    Country: "United States, United Kingdom",
    Awards: "Nominated for 13 Oscars. 252 wins & 379 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "93%",
      },
      {
        Source: "Metacritic",
        Value: "88/100",
      },
    ],
    Metascore: "88",
    imdbRating: "8.4",
    imdbVotes: "621,863",
    imdbID: "tt15398776",
    Type: "movie",
    DVD: "21 Nov 2023",
    BoxOffice: "$328,581,295",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Interstellar",
    Year: "2014",
    Rated: "PG-13",
    Released: "07 Nov 2014",
    Runtime: "169 min",
    Genre: "Adventure, Drama, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan",
    Actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    Plot: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    Language: "English",
    Country: "United States, United Kingdom, Canada",
    Awards: "Won 1 Oscar. 44 wins & 148 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "73%",
      },
      {
        Source: "Metacritic",
        Value: "74/100",
      },
    ],
    Metascore: "74",
    imdbRating: "8.7",
    imdbVotes: "2,053,873",
    imdbID: "tt0816692",
    Type: "movie",
    DVD: "24 May 2016",
    BoxOffice: "$188,020,017",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Top Gun: Maverick",
    Year: "2022",
    Rated: "PG-13",
    Released: "27 May 2022",
    Runtime: "130 min",
    Genre: "Action, Drama",
    Director: "Joseph Kosinski",
    Writer: "Jim Cash, Jack Epps Jr., Peter Craig",
    Actors: "Tom Cruise, Jennifer Connelly, Miles Teller",
    Plot: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to ...",
    Language: "English",
    Country: "United States",
    Awards: "Won 1 Oscar. 102 wins & 229 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "96%",
      },
      {
        Source: "Metacritic",
        Value: "78/100",
      },
    ],
    Metascore: "78",
    imdbRating: "8.3",
    imdbVotes: "672,058",
    imdbID: "tt1745960",
    Type: "movie",
    DVD: "22 Aug 2022",
    BoxOffice: "$718,732,821",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Wolf of Wall Street",
    Year: "2013",
    Rated: "R",
    Released: "25 Dec 2013",
    Runtime: "180 min",
    Genre: "Biography, Comedy, Crime",
    Director: "Martin Scorsese",
    Writer: "Terence Winter, Jordan Belfort",
    Actors: "Leonardo DiCaprio, Jonah Hill, Margot Robbie",
    Plot: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
    Language: "English, French",
    Country: "United States",
    Awards: "Nominated for 5 Oscars. 37 wins & 179 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.2/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "80%",
      },
      {
        Source: "Metacritic",
        Value: "75/100",
      },
    ],
    Metascore: "75",
    imdbRating: "8.2",
    imdbVotes: "1,557,215",
    imdbID: "tt0993846",
    Type: "movie",
    DVD: "12 Dec 2015",
    BoxOffice: "$116,900,694",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Avengers: Infinity War",
    Year: "2018",
    Rated: "PG-13",
    Released: "27 Apr 2018",
    Runtime: "149 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Anthony Russo, Joe Russo",
    Writer: "Christopher Markus, Stephen McFeely, Stan Lee",
    Actors: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo",
    Plot: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    Language: "English",
    Country: "United States, Norway",
    Awards: "Nominated for 1 Oscar. 46 wins & 80 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "85%",
      },
      {
        Source: "Metacritic",
        Value: "68/100",
      },
    ],
    Metascore: "68",
    imdbRating: "8.4",
    imdbVotes: "1,185,266",
    imdbID: "tt4154756",
    Type: "movie",
    DVD: "31 Jul 2018",
    BoxOffice: "$678,815,482",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "12th Fail",
    Year: "2023",
    Rated: "N/A",
    Released: "27 Oct 2023",
    Runtime: "147 min",
    Genre: "Biography, Drama",
    Director: "Vidhu Vinod Chopra",
    Writer: "Vidhu Vinod Chopra, Jaskunwar Kohli, Anurag Pathak",
    Actors: "Vikrant Massey, Medha Shankar, Joshi Anantvijay",
    Plot: "The real-life story of IPS Officer Manoj Kumar Sharma and IRS Officer Shraddha Joshi.",
    Language: "Hindi, Malayalam, Tamil, Telugu, Kannada",
    Country: "India",
    Awards: "9 wins & 11 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTJlY2U2ZmYtMzU3Ny00ZDI3LWEwMDYtOWIxNzdhZDI5ZWRkXkEyXkFqcGdeQXVyMTY3ODkyNDkz._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "91%",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.1",
    imdbVotes: "96,262",
    imdbID: "tt23849204",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Parasite",
    Year: "2019",
    Rated: "R",
    Released: "08 Nov 2019",
    Runtime: "132 min",
    Genre: "Drama, Thriller",
    Director: "Bong Joon Ho",
    Writer: "Bong Joon Ho, Han Jin-won",
    Actors: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
    Plot: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    Language: "Korean, English",
    Country: "South Korea",
    Awards: "Won 4 Oscars. 309 wins & 265 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "99%",
      },
      {
        Source: "Metacritic",
        Value: "96/100",
      },
    ],
    Metascore: "96",
    imdbRating: "8.5",
    imdbVotes: "932,313",
    imdbID: "tt6751668",
    Type: "movie",
    DVD: "11 Oct 2019",
    BoxOffice: "$53,369,749",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Poor Things",
    Year: "2023",
    Rated: "R",
    Released: "12 Jan 2024",
    Runtime: "141 min",
    Genre: "Comedy, Drama, Romance",
    Director: "Yorgos Lanthimos",
    Writer: "Tony McNamara, Alasdair Gray",
    Actors: "Emma Stone, Mark Ruffalo, Willem Dafoe",
    Plot: "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
    Language: "English, French, Portuguese",
    Country: "Ireland, United Kingdom, United States",
    Awards: "Nominated for 11 Oscars. 73 wins & 383 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGIyYWMzNjktNDE3MC00YWQyLWEyMmEtN2ZmNzZhZDk3NGJlXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.4/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.4",
    imdbVotes: "56,009",
    imdbID: "tt14230458",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$24,654,769",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Spider-Man: Across the Spider-Verse",
    Year: "2023",
    Rated: "PG",
    Released: "02 Jun 2023",
    Runtime: "140 min",
    Genre: "Animation, Action, Adventure",
    Director: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
    Writer: "Phil Lord, Christopher Miller, Dave Callaham",
    Actors: "Shameik Moore, Hailee Steinfeld, Brian Tyree Henry",
    Plot: "Miles Morales catapults across the multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a ...",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 69 wins & 168 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.6/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "95%",
      },
      {
        Source: "Metacritic",
        Value: "86/100",
      },
    ],
    Metascore: "86",
    imdbRating: "8.6",
    imdbVotes: "344,248",
    imdbID: "tt9362722",
    Type: "movie",
    DVD: "08 Aug 2023",
    BoxOffice: "$381,593,754",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Godzilla Minus One",
    Year: "2023",
    Rated: "PG-13",
    Released: "01 Dec 2023",
    Runtime: "124 min",
    Genre: "Action, Adventure, Drama",
    Director: "Takashi Yamazaki",
    Writer: "Ishirô Honda, Takeo Murata, Takashi Yamazaki",
    Actors: "Minami Hamabe, Ryunosuke Kamiki, Sakura Ando",
    Plot: "Post war Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.",
    Language: "Japanese",
    Country: "Japan",
    Awards: "Nominated for 1 Oscar. 20 wins & 49 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTI5MjNjMTMtN2NiNC00YjBlLTgzMWQtMGRhZDZkYmY1NGU2XkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "98%",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.3",
    imdbVotes: "42,785",
    imdbID: "tt23289160",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$56,418,793",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "There Will Be Blood",
    Year: "2007",
    Rated: "R",
    Released: "25 Jan 2008",
    Runtime: "158 min",
    Genre: "Drama",
    Director: "Paul Thomas Anderson",
    Writer: "Paul Thomas Anderson, Upton Sinclair",
    Actors: "Daniel Day-Lewis, Paul Dano, Ciarán Hinds",
    Plot: "A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.",
    Language: "English, American Sign ",
    Country: "United States",
    Awards: "Won 2 Oscars. 114 wins & 138 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxODQ4MDU5NV5BMl5BanBnXkFtZTcwMDU4MjU1MQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.2/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "91%",
      },
      {
        Source: "Metacritic",
        Value: "93/100",
      },
    ],
    Metascore: "93",
    imdbRating: "8.2",
    imdbVotes: "635,381",
    imdbID: "tt0469494",
    Type: "movie",
    DVD: "24 Feb 2012",
    BoxOffice: "$40,222,514",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Killers of the Flower Moon",
    Year: "2023",
    Rated: "R",
    Released: "20 Oct 2023",
    Runtime: "206 min",
    Genre: "Crime, Drama, History",
    Director: "Martin Scorsese",
    Writer: "Eric Roth, Martin Scorsese, David Grann",
    Actors: "Leonardo DiCaprio, Robert De Niro, Lily Gladstone",
    Plot: "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one - until the FBI steps in to unravel the mystery.",
    Language: "English, Sioux, Latin, French",
    Country: "United States",
    Awards: "Nominated for 10 Oscars. 105 wins & 360 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjE4ZTZlNDAtM2Q3YS00YjFhLThjN2UtODg2ZGNlN2E2MWU2XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "93%",
      },
      {
        Source: "Metacritic",
        Value: "89/100",
      },
    ],
    Metascore: "89",
    imdbRating: "7.7",
    imdbVotes: "189,347",
    imdbID: "tt5537002",
    Type: "movie",
    DVD: "05 Dec 2023",
    BoxOffice: "$67,739,778",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];

module.exports.webSeries = [
  {
    Title: "Breaking Bad",
    Year: "2008–2013",
    Rated: "TV-MA",
    Released: "20 Jan 2008",
    Runtime: "49 min",
    Genre: "Crime, Drama, Thriller",
    Director: "N/A",
    Writer: "Vince Gilligan",
    Actors: "Bryan Cranston, Aaron Paul, Anna Gunn",
    Plot: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.",
    Language: "English, Spanish",
    Country: "United States",
    Awards: "Won 16 Primetime Emmys. 157 wins & 247 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5ZDdiYjdiODU5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "96%",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.5",
    imdbVotes: "2,095,908",
    imdbID: "tt0903747",
    Type: "series",
    totalSeasons: "5",
    Response: "True",
  },
  {
    Title: "Game of Thrones",
    Year: "2011–2019",
    Rated: "TV-MA",
    Released: "17 Apr 2011",
    Runtime: "57 min",
    Genre: "Action, Adventure, Drama",
    Director: "N/A",
    Writer: "David Benioff, D.B. Weiss",
    Actors: "Emilia Clarke, Peter Dinklage, Kit Harington",
    Plot: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for a millennia.",
    Language: "English",
    Country: "United States, United Kingdom",
    Awards: "Won 59 Primetime Emmys. 389 wins & 636 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.2/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.2",
    imdbVotes: "2,250,524",
    imdbID: "tt0944947",
    Type: "series",
    totalSeasons: "8",
    Response: "True",
  },
  {
    Title: "Chernobyl",
    Year: "2019",
    Rated: "TV-MA",
    Released: "06 May 2019",
    Runtime: "330 min",
    Genre: "Drama, History, Thriller",
    Director: "N/A",
    Writer: "Craig Mazin",
    Actors: "Jessie Buckley, Jared Harris, Stellan Skarsgård",
    Plot: "This gripping mini-series tells the powerful story of the worst man-made accident in history, following the tragedy from the moment of the early-morning explosion through the chaos and loss of life in the ensuing days, weeks and m...",
    Language: "English, Russian, Ukrainian",
    Country: "United States, United Kingdom",
    Awards: "Won 10 Primetime Emmys. 84 wins & 60 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNTdkN2QwMDItMDVhNS00ZjFiLWEzNTctMzY5ODQzYWNkMDllXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.3/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.3",
    imdbVotes: "846,137",
    imdbID: "tt7366338",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
  },
  {
    Title: "Sherlock",
    Year: "2010–2017",
    Rated: "TV-14",
    Released: "24 Oct 2010",
    Runtime: "88 min",
    Genre: "Crime, Drama, Mystery",
    Director: "N/A",
    Writer: "Mark Gatiss, Steven Moffat",
    Actors: "Benedict Cumberbatch, Martin Freeman, Una Stubbs",
    Plot: "The quirky spin on Conan Doyle's iconic sleuth pitches him as a \"high-functioning sociopath\" in modern-day London. Assisting him in his investigations: Afghanistan War vet John Watson, who's introduced to Holmes by a mutual acquai...",
    Language: "English",
    Country: "United Kingdom, United States",
    Awards: "Won 9 Primetime Emmys. 93 wins & 183 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMWEzNTFlMTQtMzhjOS00MzQ1LWJjNjgtY2RhMjFhYjQwYjIzXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.1",
    imdbVotes: "986,707",
    imdbID: "tt1475582",
    Type: "series",
    totalSeasons: "4",
    Response: "True",
  },
  {
    Title: "The Sopranos",
    Year: "1999–2007",
    Rated: "TV-MA",
    Released: "10 Jan 1999",
    Runtime: "55 min",
    Genre: "Crime, Drama",
    Director: "N/A",
    Writer: "David Chase",
    Actors: "James Gandolfini, Lorraine Bracco, Edie Falco",
    Plot: "New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that affect his mental state, leading him to seek professional psychiatric counseling.",
    Language: "English, Italian, Russian",
    Country: "United States",
    Awards: "Won 21 Primetime Emmys. 126 wins & 312 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNmU3MjkzZWQtOTk1Ni00OTNiLWJhMmMtNmEyN2JjZjUzZDUyXkEyXkFqcGdeQXVyNDIyNjA2MTk@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.2/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.2",
    imdbVotes: "459,205",
    imdbID: "tt0141842",
    Type: "series",
    totalSeasons: "6",
    Response: "True",
  },
  {
    Title: "Rick and Morty",
    Year: "2013–",
    Rated: "TV-MA",
    Released: "02 Dec 2013",
    Runtime: "23 min",
    Genre: "Animation, Adventure, Comedy",
    Director: "N/A",
    Writer: "Dan Harmon, Justin Roiland",
    Actors: "Chris Parnell, Spencer Grammer, Sarah Chalke",
    Plot: "The fractured domestic lives of a nihilistic mad scientist and his anxious grandson are further complicated by their inter-dimensional misadventures.",
    Language: "English",
    Country: "United States",
    Awards: "Won 2 Primetime Emmys. 18 wins & 43 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjRjOTFkOTktZWUzMi00YzMyLThkMmYtMjEwNmQyNzliYTNmXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.1",
    imdbVotes: "591,730",
    imdbID: "tt2861424",
    Type: "series",
    totalSeasons: "8",
    Response: "True",
  },
  {
    Title: "Friends",
    Year: "1994–2004",
    Rated: "TV-14",
    Released: "22 Sep 1994",
    Runtime: "22 min",
    Genre: "Comedy, Romance",
    Director: "N/A",
    Writer: "David Crane, Marta Kauffman",
    Actors: "Jennifer Aniston, Courteney Cox, Lisa Kudrow",
    Plot: "Follows the personal and professional lives of six twenty to thirty year-old friends living in the Manhattan borough of New York City.",
    Language: "English, Spanish, Italian, French, Dutch, Hebrew",
    Country: "United States",
    Awards: "Won 6 Primetime Emmys. 79 wins & 231 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.9/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.9",
    imdbVotes: "1,074,396",
    imdbID: "tt0108778",
    Type: "series",
    totalSeasons: "10",
    Response: "True",
  },
  {
    Title: "The Office",
    Year: "2005–2013",
    Rated: "TV-14",
    Released: "24 Mar 2005",
    Runtime: "22 min",
    Genre: "Comedy",
    Director: "N/A",
    Writer: "Greg Daniels, Ricky Gervais, Stephen Merchant",
    Actors: "Steve Carell, Jenna Fischer, John Krasinski",
    Plot: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
    Language: "English, Spanish, German, French",
    Country: "United States",
    Awards: "Won 5 Primetime Emmys. 51 wins & 195 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDNkOTE4NDQtMTNmYi00MWE0LWE4ZTktYTc0NzhhNWIzNzJiXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.0",
    imdbVotes: "696,300",
    imdbID: "tt0386676",
    Type: "series",
    totalSeasons: "9",
    Response: "True",
  },
  {
    Title: "Attack on Titan",
    Year: "2013–2023",
    Rated: "TV-MA",
    Released: "28 Sep 2013",
    Runtime: "24 min",
    Genre: "Animation, Action, Adventure",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Jessie James Grelle, Bryce Papenbrook, Trina Nishimura",
    Plot: "After his hometown is destroyed and is traumatized, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.",
    Language: "Japanese",
    Country: "Japan",
    Awards: "38 wins & 89 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDFjYTIxMjctYTQ2ZC00OGQ4LWE3OGYtNDdiMzNiNDZlMDAwXkEyXkFqcGdeQXVyNzI3NjY3NjQ@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.1",
    imdbVotes: "494,261",
    imdbID: "tt2560140",
    Type: "series",
    totalSeasons: "4",
    Response: "True",
  },
  {
    Title: "Better Call Saul",
    Year: "2015–2022",
    Rated: "TV-MA",
    Released: "08 Feb 2015",
    Runtime: "46 min",
    Genre: "Crime, Drama",
    Director: "N/A",
    Writer: "Vince Gilligan, Peter Gould",
    Actors: "Bob Odenkirk, Rhea Seehorn, Jonathan Banks",
    Plot: "The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman.",
    Language: "English, Spanish, Vietnamese",
    Country: "United States",
    Awards: "Nominated for 53 Primetime Emmys. 68 wins & 323 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZDA4YmE0OTYtMmRmNS00Mzk2LTlhM2MtNjk4NzBjZGE1MmIyXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.0",
    imdbVotes: "633,100",
    imdbID: "tt3032476",
    Type: "series",
    totalSeasons: "6",
    Response: "True",
  },
  {
    Title: "Stranger Things",
    Year: "2016–2025",
    Rated: "TV-14",
    Released: "15 Jul 2016",
    Runtime: "51 min",
    Genre: "Drama, Fantasy, Horror",
    Director: "N/A",
    Writer: "Matt Duffer, Ross Duffer",
    Actors: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder",
    Plot: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    Language: "Russian, English",
    Country: "United States",
    Awards: "Won 12 Primetime Emmys. 112 wins & 312 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.7",
    imdbVotes: "1,311,634",
    imdbID: "tt4574334",
    Type: "series",
    totalSeasons: "5",
    Response: "True",
  },
  {
    Title: "True Detective",
    Year: "2014–",
    Rated: "TV-MA",
    Released: "12 Jan 2014",
    Runtime: "55 min",
    Genre: "Crime, Drama, Mystery",
    Director: "N/A",
    Writer: "Nic Pizzolatto, Issa López",
    Actors: "Vince Vaughn, Colin Farrell, Rachel McAdams",
    Plot: "Anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.",
    Language: "English",
    Country: "United States",
    Awards: "Won 5 Primetime Emmys. 30 wins & 93 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNTEzMzBiNGYtYThiZS00MzBjLTk5ZWItM2FmMzU3Y2RjYTVlXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.9/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.9",
    imdbVotes: "636,491",
    imdbID: "tt2356777",
    Type: "series",
    totalSeasons: "4",
    Response: "True",
  },
  {
    Title: "Peaky Blinders",
    Year: "2013–2022",
    Rated: "TV-MA",
    Released: "30 Sep 2014",
    Runtime: "60 min",
    Genre: "Crime, Drama",
    Director: "N/A",
    Writer: "Steven Knight",
    Actors: "Cillian Murphy, Paul Anderson, Sophie Rundle",
    Plot: "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.",
    Language: "English, Romanian, Irish Gaelic, Italian, Yiddish, French",
    Country: "United Kingdom",
    Awards: "Won 1 BAFTA Award23 wins & 55 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjYzZDgzMmYtYjY5Zi00YTk1LThhMDYtNjFlNzM4MTZhYzgyXkEyXkFqcGdeQXVyMTE5NDQ1MzQ3._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.8",
    imdbVotes: "632,567",
    imdbID: "tt2442560",
    Type: "series",
    totalSeasons: "6",
    Response: "True",
  },
  {
    Title: "The Last of Us",
    Year: "2023–",
    Rated: "TV-MA",
    Released: "15 Jan 2023",
    Runtime: "18S min",
    Genre: "Action, Adventure, Drama",
    Director: "N/A",
    Writer: "Neil Druckmann, Craig Mazin",
    Actors: "Pedro Pascal, Bella Ramsey, Anna Torv",
    Plot: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
    Language: "English, Indonesian",
    Country: "Canada, United States",
    Awards: "Won 8 Primetime Emmys. 42 wins & 126 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZGUzYTI3M2EtZmM0Yy00NGUyLWI4ODEtN2Q3ZGJlYzhhZjU3XkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.8",
    imdbVotes: "489,723",
    imdbID: "tt3581920",
    Type: "series",
    totalSeasons: "2",
    Response: "True",
  },
  {
    Title: "The Boys",
    Year: "2019–",
    Rated: "TV-MA",
    Released: "26 Jul 2019",
    Runtime: "31S min",
    Genre: "Action, Comedy, Crime",
    Director: "N/A",
    Writer: "Eric Kripke",
    Actors: "Karl Urban, Jack Quaid, Antony Starr",
    Plot: "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
    Language: "English",
    Country: "United States",
    Awards: "Won 1 Primetime Emmy. 21 wins & 82 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZGUyNzM0M2EtMjA1Zi00MWJhLWI2ZWEtNzE3OTgyMTBkN2IzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.7",
    imdbVotes: "623,289",
    imdbID: "tt1190634",
    Type: "series",
    totalSeasons: "4",
    Response: "True",
  },
  {
    Title: "Dark",
    Year: "2017–2020",
    Rated: "TV-MA",
    Released: "01 Dec 2017",
    Runtime: "60 min",
    Genre: "Crime, Drama, Mystery",
    Director: "N/A",
    Writer: "Baran bo Odar, Jantje Friese",
    Actors: "Louis Hofmann, Karoline Eichhorn, Lisa Vicari",
    Plot: "A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.",
    Language: "German",
    Country: "Germany, United States",
    Awards: "8 wins & 25 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTk2NzUyOTctZDdlMS00MDJlLTgzNTEtNzQzYjFhNjA0YjBjXkEyXkFqcGdeQXVyMjg1NDcxNDE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.7",
    imdbVotes: "435,608",
    imdbID: "tt5753856",
    Type: "series",
    totalSeasons: "3",
    Response: "True",
  },
  {
    Title: "Narcos",
    Year: "2015–2017",
    Rated: "TV-MA",
    Released: "28 Aug 2015",
    Runtime: "49 min",
    Genre: "Biography, Crime, Drama",
    Director: "N/A",
    Writer: "Carlo Bernard, Chris Brancato, Doug Miro",
    Actors: "Pedro Pascal, Wagner Moura, Boyd Holbrook",
    Plot: "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.",
    Language: "English, Spanish",
    Country: "United States, Colombia",
    Awards: "Nominated for 3 Primetime Emmys. 8 wins & 20 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNmFjODU3YzgtMGUwNC00ZGI3LWFkZjQtMjkxZDc3NmQ1MzcyXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.8",
    imdbVotes: "462,749",
    imdbID: "tt2707408",
    Type: "series",
    totalSeasons: "3",
    Response: "True",
  },
  {
    Title: "Daredevil",
    Year: "2015–2018",
    Rated: "TV-MA",
    Released: "10 Apr 2015",
    Runtime: "54 min",
    Genre: "Action, Crime, Drama",
    Director: "N/A",
    Writer: "Drew Goddard",
    Actors: "Charlie Cox, Vincent D'Onofrio, Deborah Ann Woll",
    Plot: "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.",
    Language: "English, Spanish, Mandarin, Japanese, Russian",
    Country: "United States",
    Awards: "Nominated for 5 Primetime Emmys. 9 wins & 43 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BODcwOTg2MDE3NF5BMl5BanBnXkFtZTgwNTUyNTY1NjM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.6",
    imdbVotes: "470,084",
    imdbID: "tt3322312",
    Type: "series",
    totalSeasons: "3",
    Response: "True",
  },
  {
    Title: "Money Heist",
    Year: "2017–2021",
    Rated: "TV-MA",
    Released: "02 May 2017",
    Runtime: "70 min",
    Genre: "Action, Crime, Drama",
    Director: "N/A",
    Writer: "Álex Pina",
    Actors: "Álvaro Morte, Itziar Ituño, Pedro Alonso",
    Plot: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
    Language: "Spanish, Russian, Serbian, English",
    Country: "Spain",
    Awards: "38 wins & 45 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BODI0ZTljYTMtODQ1NC00NmI0LTk1YWUtN2FlNDM1MDExMDlhXkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.2/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.2",
    imdbVotes: "524,117",
    imdbID: "tt6468322",
    Type: "series",
    totalSeasons: "5",
    Response: "True",
  },
  {
    Title: "Squid Game",
    Year: "2021–",
    Rated: "TV-MA",
    Released: "17 Sep 2021",
    Runtime: "N/A",
    Genre: "Action, Drama, Mystery",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Lee Jung-jae, Park Hae-soo, Dylan Besseau",
    Plot: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes: a survival game that has a whopping 45.6 billion-won prize at stake.",
    Language: "Korean, English, Urdu",
    Country: "South Korea",
    Awards: "Won 6 Primetime Emmys. 47 wins & 85 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYWE3MDVkN2EtNjQ5MS00ZDQ4LTliNzYtMjc2YWMzMDEwMTA3XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.0",
    imdbVotes: "525,720",
    imdbID: "tt10919420",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
  },
];
